// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinGo.Qap.Platform.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MinGo.Qap.Platform.Migrations
{
    [DbContext(typeof(PlatformDbContext))]
    [Migration("20260507170506_RemoveClusterAndDeclarativeJob")]
    partial class RemoveClusterAndDeclarativeJob
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MinGo.Qap.Platform.Data.Entities.Agent", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("LastHeartbeat")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("LastReportedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TokenHash")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("LastHeartbeat");

                    b.HasIndex("Status");

                    b.ToTable("Agents", (string)null);
                });

            modelBuilder.Entity("MinGo.Qap.Platform.Data.Entities.AgentScheduler", b =>
                {
                    b.Property<string>("AgentId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SchedulerInfoId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("AgentId", "SchedulerInfoId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("SchedulerInfoId");

                    b.ToTable("AgentSchedulers", (string)null);
                });

            modelBuilder.Entity("MinGo.Qap.Platform.Data.Entities.JobDefinition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Group")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("JobKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Options")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Params")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResultJson")
                        .HasColumnType("text");

                    b.Property<string>("Schedule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("SchedulerName", "JobKey")
                        .IsUnique();

                    b.ToTable("JobDefinitions", (string)null);
                });

            modelBuilder.Entity("MinGo.Qap.Platform.Data.Entities.SchedulerInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("FirstReportedAt")
                        .HasColumnType("timestamptz");

                    b.Property<bool>("IsClustered")
                        .HasColumnType("boolean");

                    b.Property<string>("JobStoreType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("LastReportedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("NumberOfJobsExecuted")
                        .HasColumnType("integer");

                    b.Property<string>("PropertiesJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RunningSince")
                        .HasColumnType("timestamptz");

                    b.Property<string>("SchedulerInstanceId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("SchedulerName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ThreadPoolSize")
                        .HasColumnType("integer");

                    b.Property<string>("ThreadPoolType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Version")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("LastReportedAt");

                    b.HasIndex("Status");

                    b.HasIndex("SchedulerName", "SchedulerInstanceId")
                        .IsUnique();

                    b.ToTable("SchedulerInfos", (string)null);
                });

            modelBuilder.Entity("MinGo.Qap.Platform.Data.Entities.AgentScheduler", b =>
                {
                    b.HasOne("MinGo.Qap.Platform.Data.Entities.Agent", "Agent")
                        .WithMany("AgentSchedulers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MinGo.Qap.Platform.Data.Entities.SchedulerInfo", "SchedulerInfo")
                        .WithMany("AgentSchedulers")
                        .HasForeignKey("SchedulerInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("SchedulerInfo");
                });

            modelBuilder.Entity("MinGo.Qap.Platform.Data.Entities.Agent", b =>
                {
                    b.Navigation("AgentSchedulers");
                });

            modelBuilder.Entity("MinGo.Qap.Platform.Data.Entities.SchedulerInfo", b =>
                {
                    b.Navigation("AgentSchedulers");
                });
#pragma warning restore 612, 618
        }
    }
}
